spotify_client_id: "SPOTIFY_CLIENT_ID"
spotify_client_secret: "SPOTIFY_CLIENT_SECRET"
spotify_redirect_uri: "http://127.0.0.1:8000/auth/spotify/callback"

# Update the redirect uri so that it should match the uri you are visiting the server from the browser
# also configure it in the SPOTIFY DEVELOPER DASHBOARD

# control mode: mpris or mpv
control_mode: "mpris" 

# Spotify mode: ytdlp or sp_client
spotify_mode: "sp_client"


# AVOID TRAILING SLASH
# Remember to replace you user with your username $USER
scopes:
  - "/home/user/Music"
  - "/mnt/media"
  - "/var/data/public"

forbidden_scopes:
  - "/home/msm/.config"